module GuranyaHelper
    def valid_joke?(j_type)
        
        j_type.in?(['general','programming','knock-knock'])
    end

    def valid_num?(num)
        num.scan(/\D/).empty?
    end

    def valid_cat?(cat)
        cat.in?([
            "Abyssinian",
            "Aegean",
            "American",
            "Arabian Mau",
            "Australian Mist",
            "Asian",
            "Balinese",
            "Bambino",
            "Bengal",
            "Birman",
            "Bombay",
            "Brazilian",
            "British",
            "British Shorthair",
            "British Longhair",
            "Burmese",
            "Burmilla",
            "California Spangled",
            "Chantilly-Tiffany",
            "Chartreux",
            "Chausie",
            "Cheetoh",
            "Colorpoint Shorthair",
            "Cornish Rex",
            "Cymric",
            "Cyprus",
            "Devon Rex",
            "Donskoy",
            "Dragon Li",
            "Dwarf cat",
            "Egyptian Mau",
            "European Shorthair",
            "Exotic Shorthair",
            "Foldex",
            "German Rex",
            "Havana Brown",
            "Highlander",
            "Himalayan",
            "Japanese Bobtail",
            "Javanese",
            "Karelian Bobtail",
            "Khao Manee",
            "Korat",
            "Korean Bobtail",
            "Korn Ja",
            "Kurilian Bobtail",
            "LaPerm",
            "Lykoi",
            "Maine Coon",
            "Manx",
            "Mekong Bobtail",
            "Minskin",
            "Munchkin",
            "Nebelung",
            "Napoleon",
            "Norwegian Forest cat",
            "Ocicat",
            "Ojos Azules",
            "Oregon Rex",
            "Oriental Bicolor",
            "Oriental Shorthair",
            "Oriental Longhair",
            "PerFold",
            "Persian",
            "Peterbald",
            "Pixie-bob",
            "Raas",
            "Ragamuffin",
            "Ragdoll",
            "Russian Blue",
            "Russian White, Black and Tabby",
            "Sam Sawet",
            "Savannah",
            "Scottish Fold",
            "Selkirk Rex",
            "Serengeti",
            "Serrade petit",
            "Siamese",
            "Siberian",
            "Singapura",
            "Snowshoe",
            "Sokoke",
            "Somali",
            "Sphynx",
            "Suphalak",
            "Thai",
            "Thai Lilac",
            "Tonkinese",
            "Toyger",
            "Turkish Angora",
            "Turkish Van",
            "Ukrainian Levkoy"
          ])
    end

end
